name: Remix Deploy
on: push

env:
    AWS_REGION: "us-east-1"

permissions:
    id-token: write # This is required for requesting the JWT
    contents: read # This is required for actions/checkout

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            #   Is this step needed?
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                cache: npm
                cache-dependency-path: ./package.json
                node-version: 18

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-to-assume: ${{ secrets.AWS_REMIX_ROLE_ARN }}
                role-session-name: GitHub_to_AWS_via_FederatedOIDC
                aws-region: ${{ env.AWS_REGION }}

            - name: Deploy App
              run: |
                npm i && npx sst deploy --stage prod